name = "my-worker"
type = "javascript"

account_id = "f45876fbcaf4581a59ebf9ddb5549818"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-12-10"
kv_namespaces = [ 
	 { binding = "INTERVIEW_KV", preview_id = "fd4b76cada594516935c8092cf34227d", id= "fd4b76cada594516935c8092cf34227d" }
]
